FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod tidy

COPY . .

RUN go build -tags netgo -ldflags '-s -w' -o ./_bin/restapi ./_cmd

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/_bin .

EXPOSE 8080

CMD ["./restapi"]